using System;

using System.Collections.Generic;



namespace CrossFade.Potions

{



    // Rarity tiers used for weighted potion rolling and value scaling.

    public enum PotionRarity

    {

        Common,

        Uncommon,

        Rare,

        Epic,

        Legendary

    }





    // Core effect catalog used by rolling, mixing, and application layers.
    // Money gained is added every ten seconds, RewardMultiplier depends on stats effect numeric threshold
    public enum EffectType

    {

        Nausea,

        Focus, // visibility, spotlight

        Speed,

        Luck,

        RewardMultiplier,

        AccuracyModifier

    }





    // Static effect range configuration used when building potion instances.

    [Serializable]

    public class EffectRange

    {

        public EffectType EffectType;

        public float MinValue;

        public float MaxValue;

    }





    // Base potion template data (author-defined, non-rolled fields).

    [Serializable]

    public class PotionTemplate

    {

        public string TemplateId = string.Empty;

        public string DisplayName = string.Empty;

        public PotionRarity Rarity = PotionRarity.Common;

        public List<EffectRange> AvailableEffects = new();

    }





    // A rolled effect value on a runtime potion instance.

    [Serializable]

    public class PotionEffectValue

    {

        public EffectType EffectType;

        public float Value;



        public PotionEffectValue()

        {

        }



        public PotionEffectValue(EffectType effectType, float value)

        {

            EffectType = effectType;

            Value = value;

        }

    }





    // Runtime potion instance generated by the roll system.

    [Serializable]

    public class PotionData

    {

        public string InstanceId = Guid.NewGuid().ToString();

        public string Name = string.Empty;

        public PotionRarity Rarity = PotionRarity.Common;

        public List<PotionEffectValue> Effects = new();

        public bool IsConsumed;



        public PotionData()

        {

        }



        public PotionData(IReadOnlyList<PotionEffectValue> effects, PotionRarity rarity, string name)

        {

            Rarity = rarity;

            Name = name ?? string.Empty;

            if (effects == null)

            {

                Effects = new List<PotionEffectValue>();

                return;

            }

            Effects = new List<PotionEffectValue>(effects.Count);

            for (var i = 0; i < effects.Count; i++)

            {

                var e = effects[i];

                Effects.Add(new PotionEffectValue(e.EffectType, e.Value));

            }

        }



        // Returns true if this potion currently contains the requested effect.



        // effectType: Effect to check for in this potion.

        public bool HasEffect(EffectType effectType)

        {

            // 1) Loop over Effects list.

            // 2) Compare each entry EffectType with requested value.

            // 3) Return true on first match, otherwise false.

            var list = Effects;

            if (list == null)

            {

                return false;

            }

            for (var i = 0; i < list.Count; i++)

            {

                if (list[i].EffectType == effectType)

                {

                    return true;

                }

            }

            return false;

        }



        // Gets the rolled value for an effect if present, else returns 0f.



        // effectType: Effect whose value should be returned.

        public float GetEffectValue(EffectType effectType)

        {

            // 1) Search Effects list for matching EffectType.

            // 2) Return matched Value.

            // 3) Return 0f when effect is not found.

            var list = Effects;

            if (list == null)

            {

                return 0f;

            }

            for (var i = 0; i < list.Count; i++)

            {

                if (list[i].EffectType == effectType)

                {

                    return list[i].Value;

                }

            }

            return 0f;

        }

    }

}


