using System;
using System.Collections.Generic;

namespace CrossFade.Potions
{
    
    // Rarity tiers used for weighted potion rolling and value scaling.
    public enum PotionRarity
    {
        Common,
        Uncommon,
        Rare,
        Epic,
        Legendary
    }

    
    // Core effect catalog used by rolling, mixing, and application layers.
    public enum EffectType
    {
        Nausea,
        Focus,
        Speed,
        Luck,
        RewardMultiplier,
        AccuracyModifier
    }

    
    // Static effect range configuration used when building potion instances.
    [Serializable]
    public class EffectRange
    {
        public EffectType EffectType;
        public float MinValue;
        public float MaxValue;
    }

    
    // Base potion template data (author-defined, non-rolled fields).
    [Serializable]
    public class PotionTemplate
    {
        public string TemplateId = string.Empty;
        public string DisplayName = string.Empty;
        public PotionRarity Rarity = PotionRarity.Common;
        public List<EffectRange> AvailableEffects = new();
    }

    
    // A rolled effect value on a runtime potion instance.
    [Serializable]
    public class PotionEffectValue
    {
        public EffectType EffectType;
        public float Value;
    }

    
    // Runtime potion instance generated by the roll system.
    [Serializable]
    public class PotionData
    {
        public string InstanceId = Guid.NewGuid().ToString();
        public string Name = string.Empty;
        public PotionRarity Rarity = PotionRarity.Common;
        public List<PotionEffectValue> Effects = new();
        public bool IsConsumed;

        
        // Returns true if this potion currently contains the requested effect.

        // effectType: Effect to check for in this potion.
        public bool HasEffect(EffectType effectType)
        {
            // 1) Loop over Effects list.
            // 2) Compare each entry EffectType with requested value.
            // 3) Return true on first match, otherwise false.
            throw new NotImplementedException();
        }

        
        // Gets the rolled value for an effect if present, else returns 0f.

        // effectType: Effect whose value should be returned.
        public float GetEffectValue(EffectType effectType)
        {
            // 1) Search Effects list for matching EffectType.
            // 2) Return matched Value.
            // 3) Return 0f when effect is not found.
            throw new NotImplementedException();
        }
    }
}
